/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Sebastian Lague (https://sketchfab.com/SebastianL)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/low-poly-character-rigged-b2ca55ab706c4b1ba1c6475d8b3c5bfd
Title: Low poly character (rigged)
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function Alex(props) {
  const { nodes, materials } = useGLTF("/assets/models/low_poly_character_rigged.glb");
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group scale={0.282}>
          <primitive object={nodes.Armature_rootJoint} />
          <mesh
            receiveShadow
            geometry={nodes.Character_1.geometry}
            material={materials.Character}
            position={[0.052, -0.058, 0]}
            scale={7.292}
          />
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/assets/models/low_poly_character_rigged.glb");
